# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import custom_node_service_pb2 as custom__node__service__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in custom_node_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CustomNodeExecutorStub(object):
    """=============================================================================
    서비스 정의
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteNode = channel.unary_unary(
                '/aicanvas.customnode.v1.CustomNodeExecutor/ExecuteNode',
                request_serializer=custom__node__service__pb2.NodeRequest.SerializeToString,
                response_deserializer=custom__node__service__pb2.NodeResponse.FromString,
                _registered_method=True)
        self.ExecuteNodeStream = channel.unary_stream(
                '/aicanvas.customnode.v1.CustomNodeExecutor/ExecuteNodeStream',
                request_serializer=custom__node__service__pb2.NodeRequest.SerializeToString,
                response_deserializer=custom__node__service__pb2.NodeProgress.FromString,
                _registered_method=True)
        self.RegisterNode = channel.unary_unary(
                '/aicanvas.customnode.v1.CustomNodeExecutor/RegisterNode',
                request_serializer=custom__node__service__pb2.NodeDefinition.SerializeToString,
                response_deserializer=custom__node__service__pb2.RegistrationResult.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/aicanvas.customnode.v1.CustomNodeExecutor/HealthCheck',
                request_serializer=custom__node__service__pb2.HealthRequest.SerializeToString,
                response_deserializer=custom__node__service__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.CancelExecution = channel.unary_unary(
                '/aicanvas.customnode.v1.CustomNodeExecutor/CancelExecution',
                request_serializer=custom__node__service__pb2.CancelRequest.SerializeToString,
                response_deserializer=custom__node__service__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.GetExecutionStatus = channel.unary_unary(
                '/aicanvas.customnode.v1.CustomNodeExecutor/GetExecutionStatus',
                request_serializer=custom__node__service__pb2.StatusRequest.SerializeToString,
                response_deserializer=custom__node__service__pb2.ExecutionStatus.FromString,
                _registered_method=True)
        self.ListNodes = channel.unary_unary(
                '/aicanvas.customnode.v1.CustomNodeExecutor/ListNodes',
                request_serializer=custom__node__service__pb2.ListNodesRequest.SerializeToString,
                response_deserializer=custom__node__service__pb2.ListNodesResponse.FromString,
                _registered_method=True)
        self.DeleteNode = channel.unary_unary(
                '/aicanvas.customnode.v1.CustomNodeExecutor/DeleteNode',
                request_serializer=custom__node__service__pb2.DeleteNodeRequest.SerializeToString,
                response_deserializer=custom__node__service__pb2.DeleteNodeResponse.FromString,
                _registered_method=True)


class CustomNodeExecutorServicer(object):
    """=============================================================================
    서비스 정의
    =============================================================================

    """

    def ExecuteNode(self, request, context):
        """단일 노드를 즉시 응답과 함께 실행
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteNodeStream(self, request, context):
        """스트리밍 진행 업데이트와 함께 노드 실행
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterNode(self, request, context):
        """커스텀 노드 등록 및 검증
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """커스텀 노드 서버의 상태 확인
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelExecution(self, request, context):
        """실행 중인 작업 취소
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExecutionStatus(self, request, context):
        """실행 상태 조회
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNodes(self, request, context):
        """사용 가능한 커스텀 노드 목록 조회
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNode(self, request, context):
        """커스텀 노드 삭제
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomNodeExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteNode': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteNode,
                    request_deserializer=custom__node__service__pb2.NodeRequest.FromString,
                    response_serializer=custom__node__service__pb2.NodeResponse.SerializeToString,
            ),
            'ExecuteNodeStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteNodeStream,
                    request_deserializer=custom__node__service__pb2.NodeRequest.FromString,
                    response_serializer=custom__node__service__pb2.NodeProgress.SerializeToString,
            ),
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=custom__node__service__pb2.NodeDefinition.FromString,
                    response_serializer=custom__node__service__pb2.RegistrationResult.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=custom__node__service__pb2.HealthRequest.FromString,
                    response_serializer=custom__node__service__pb2.HealthResponse.SerializeToString,
            ),
            'CancelExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelExecution,
                    request_deserializer=custom__node__service__pb2.CancelRequest.FromString,
                    response_serializer=custom__node__service__pb2.CancelResponse.SerializeToString,
            ),
            'GetExecutionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExecutionStatus,
                    request_deserializer=custom__node__service__pb2.StatusRequest.FromString,
                    response_serializer=custom__node__service__pb2.ExecutionStatus.SerializeToString,
            ),
            'ListNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNodes,
                    request_deserializer=custom__node__service__pb2.ListNodesRequest.FromString,
                    response_serializer=custom__node__service__pb2.ListNodesResponse.SerializeToString,
            ),
            'DeleteNode': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNode,
                    request_deserializer=custom__node__service__pb2.DeleteNodeRequest.FromString,
                    response_serializer=custom__node__service__pb2.DeleteNodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aicanvas.customnode.v1.CustomNodeExecutor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aicanvas.customnode.v1.CustomNodeExecutor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CustomNodeExecutor(object):
    """=============================================================================
    서비스 정의
    =============================================================================

    """

    @staticmethod
    def ExecuteNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aicanvas.customnode.v1.CustomNodeExecutor/ExecuteNode',
            custom__node__service__pb2.NodeRequest.SerializeToString,
            custom__node__service__pb2.NodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteNodeStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aicanvas.customnode.v1.CustomNodeExecutor/ExecuteNodeStream',
            custom__node__service__pb2.NodeRequest.SerializeToString,
            custom__node__service__pb2.NodeProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aicanvas.customnode.v1.CustomNodeExecutor/RegisterNode',
            custom__node__service__pb2.NodeDefinition.SerializeToString,
            custom__node__service__pb2.RegistrationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aicanvas.customnode.v1.CustomNodeExecutor/HealthCheck',
            custom__node__service__pb2.HealthRequest.SerializeToString,
            custom__node__service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aicanvas.customnode.v1.CustomNodeExecutor/CancelExecution',
            custom__node__service__pb2.CancelRequest.SerializeToString,
            custom__node__service__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExecutionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aicanvas.customnode.v1.CustomNodeExecutor/GetExecutionStatus',
            custom__node__service__pb2.StatusRequest.SerializeToString,
            custom__node__service__pb2.ExecutionStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aicanvas.customnode.v1.CustomNodeExecutor/ListNodes',
            custom__node__service__pb2.ListNodesRequest.SerializeToString,
            custom__node__service__pb2.ListNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aicanvas.customnode.v1.CustomNodeExecutor/DeleteNode',
            custom__node__service__pb2.DeleteNodeRequest.SerializeToString,
            custom__node__service__pb2.DeleteNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
