#!/usr/bin/env python
"""Proto 파일을 Python 코드로 컴파일"""

import subprocess
import sys
from pathlib import Path


def fix_imports(output_dir: Path):
    """생성된 파일의 import 경로를 수정"""
    for grpc_file in output_dir.glob("*_pb2_grpc.py"):
        content = grpc_file.read_text()
        # 상대 import로 수정
        base_name = grpc_file.stem.replace("_pb2_grpc", "")
        content = content.replace(f"import {base_name}_pb2", f"from . import {base_name}_pb2")
        grpc_file.write_text(content)
        print(f"  Import 수정됨: {grpc_file.name}")


def compile_protos():
    root_dir = Path(__file__).parent.parent
    proto_dir = root_dir / "proto"
    output_dir = root_dir / "aicanvas" / "grpc"

    # proto 디렉토리 확인
    if not proto_dir.exists():
        print(f" Proto 디렉토리가 없습니다: {proto_dir}")
        sys.exit(1)

    # proto 파일 찾기
    proto_files = list(proto_dir.glob("*.proto"))

    if not proto_files:
        print(f"Proto 파일이 없습니다: {proto_dir}")
        sys.exit(1)

    print(f"Proto 디렉토리: {proto_dir}")
    print(f"발견된 proto 파일: {[f.name for f in proto_files]}")

    # 출력 디렉토리 생성
    output_dir.mkdir(parents=True, exist_ok=True)
    print(f"출력 디렉토리: {output_dir}")

    # 각 proto 파일 컴파일
    for proto_file in proto_files:
        print(f"\n컴파일 중: {proto_file.name}")

        cmd = [
            "python",
            "-m",
            "grpc_tools.protoc",
            f"--proto_path={proto_dir}",
            f"--python_out={output_dir}",
            f"--grpc_python_out={output_dir}",
            f"--pyi_out={output_dir}",  # 타입 힌트 파일도 생성
            str(proto_file),  # 구체적인 파일 경로
        ]

        try:
            result = subprocess.run(cmd, check=True, capture_output=True, text=True)
            print(f"   성공: {proto_file.name}")

            # 생성된 파일 확인
            base_name = proto_file.stem
            generated_files = [
                output_dir / f"{base_name}_pb2.py",
                output_dir / f"{base_name}_pb2_grpc.py",
                output_dir / f"{base_name}_pb2.pyi",
            ]

            for gen_file in generated_files:
                if gen_file.exists():
                    print(f"   생성됨: {gen_file.name}")

        except subprocess.CalledProcessError as e:
            print(f"   실패: {proto_file.name}")
            print(f"   에러: {e.stderr}")
            sys.exit(1)

    # import 경로 수정
    fix_imports(output_dir)

    # __init__.py 파일 생성으로 패키지화
    init_file = output_dir / "__init__.py"
    if not init_file.exists():
        init_file.write_text(
            '"""Generated gRPC code from proto files"""\n# This file was auto-generated by compile_protos.py\n'
        )
        print(f"\n생성됨: {init_file.name}")

    print("\nProto 컴파일 완료!")
    print(f"생성된 파일들이 {output_dir}에 있습니다.")


if __name__ == "__main__":
    compile_protos()
